# Generated by Django 5.0.6 on 2024-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.CharField(max_length=300)),
                ('shorturl', models.CharField(max_length=7)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
